### ISSUE TITLE
Receive warning when using resizeMode in style

### ISSUE THREAD

**Issue by pcguru** [kfiroo/react-native-cached-image#1]
Whenever I use resizeMode in style I get a React warning:
Warning: Failed prop type: Invalid props.style key 'resizeMode' supplied to 'ActivityIndicator'.

It seems as if the style given to CachedImage is used on both the `ActivityIndicator` and the `Image` elements. Is there a way to get the separate styles to them?

```
<CachedImage
  useQueryParamsInCacheKey
  style={{ resizeMode: 'contain' }}
  source={uri}
/>
```

**Comment by kfiroo** [comment]
@pcguru Hey, Thanks for this.
The goal was to avoid having to declare the style twice and that the `ActivityIndicator` would fit in the image's place seamlessly.

Maybe you could use the 'resizeMode' prop instead of the style? [see docs](https://facebook.github.io/react-native/docs/image.html#resizemode)
